[servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_user=ubuntu
ansible_ssh_private_key_file=jumpserver.pem #copy your pem file from local o server using scp

[servers]
13.206.202.58 #second server ip addr


# Command to RUN
# ansible-playbook -i hosts.ini install_apache.yml
